name: test-cron-every-2-min

on:
  schedule:
    - cron: '*/2 * * * *'  # every 2 minutes
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: |
          echo "Current time: $(date -u)"

      - name: Test complete
        run: echo "Cron job ran successfully!"
